# Generated by Django 2.0.6 on 2018-06-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20180609_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_html',
        ),
    ]
